import { SearchTrack } from '../types';

export const CURATED_CATEGORIES = [
  'All Hits',
  'Party Starters',
  'Rock & 80s Classics',
  'Pop & Today',
  'R&B & Soul',
  'Heartfelt Ballads',
  'OPM Hits',
  'Disney & Musicals',
  'Anime & J-Pop',
  'Duets & Groups',
];

export const POPULAR_KARAOKE_SONGS: SearchTrack[] = [
  // Party Starters & Rock
  {
    video_id: '8yvGCAvOAfM',
    title: 'Queen - Bohemian Rhapsody (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    duration: '5:55',
    category: 'Rock & 80s Classics',
  },
  {
    video_id: '1k8craCGpgs',
    title: "Journey - Don't Stop Believin' (Karaoke Version)",
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
    duration: '4:11',
    category: 'Rock & 80s Classics',
  },
  {
    video_id: 'fJ9rUzIMcZQ',
    title: 'Queen - Don’t Stop Me Now (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    duration: '3:30',
    category: 'Party Starters',
  },
  {
    video_id: 'hT_nvWreIhg',
    title: 'Bon Jovi - Livin’ On A Prayer (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    duration: '4:09',
    category: 'Rock & 80s Classics',
  },
  {
    video_id: 'L0MK7qz13bU',
    title: 'ABBA - Dancing Queen (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&auto=format&fit=crop&q=80',
    duration: '3:50',
    category: 'Party Starters',
  },
  {
    video_id: '450p7goxZqg',
    title: 'John Legend - All Of Me (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1520523839898-507124cd5333?w=600&auto=format&fit=crop&q=80',
    duration: '4:30',
    category: 'Heartfelt Ballads',
  },
  {
    video_id: 'rYEDA3JcQqw',
    title: 'Adele - Rolling In The Deep (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
    duration: '3:48',
    category: 'Pop & Today',
  },
  {
    video_id: '09R8_2nJtjg',
    title: 'Bruno Mars - Uptown Funk (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&auto=format&fit=crop&q=80',
    duration: '4:30',
    category: 'Party Starters',
  },
  {
    video_id: 'YQHsXMglC9A',
    title: 'Adele - Someone Like You (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1445985543470-41fdd6ce388d?w=600&auto=format&fit=crop&q=80',
    duration: '4:45',
    category: 'Heartfelt Ballads',
  },
  {
    video_id: 'GzU8KqOY8YA',
    title: 'Miley Cyrus - Flowers (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
    duration: '3:20',
    category: 'Pop & Today',
  },
  {
    video_id: 'jg09X49fHJU',
    title: 'Ed Sheeran - Perfect (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80',
    duration: '4:23',
    category: 'Heartfelt Ballads',
  },
  {
    video_id: 'HL1UzIK-flA',
    title: 'Frank Sinatra - My Way (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
    duration: '4:35',
    category: 'Rock & 80s Classics',
  },
  {
    video_id: 'bo_efYhAK2A',
    title: 'Lady Gaga, Bradley Cooper - Shallow (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&auto=format&fit=crop&q=80',
    duration: '3:36',
    category: 'Duets & Groups',
  },
  {
    video_id: 'nfWlot6h_JM',
    title: 'Taylor Swift - Shake It Off (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=600&auto=format&fit=crop&q=80',
    duration: '3:39',
    category: 'Pop & Today',
  },
  {
    video_id: 'kffacxfA7G4',
    title: 'Justin Bieber - Baby (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    duration: '3:35',
    category: 'Pop & Today',
  },
  {
    video_id: 'CevxZvSJLk8',
    title: 'Katy Perry - Roar (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
    duration: '3:45',
    category: 'Pop & Today',
  },
  {
    video_id: '60ItHLz5WEA',
    title: 'Alan Walker - Faded (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    duration: '3:32',
    category: 'Pop & Today',
  },
  {
    video_id: 'fLexgOxsZu0',
    title: 'Bruno Mars - When I Was Your Man (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1520523839898-507124cd5333?w=600&auto=format&fit=crop&q=80',
    duration: '3:33',
    category: 'Heartfelt Ballads',
  },
  {
    video_id: 'RgKAFK5djSk',
    title: 'Wiz Khalifa ft. Charlie Puth - See You Again (Karaoke)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
    duration: '3:50',
    category: 'Pop & Today',
  },
  {
    video_id: 'OPf0YbXqDm0',
    title: 'Mark Ronson ft. Bruno Mars - 24K Magic (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&auto=format&fit=crop&q=80',
    duration: '3:46',
    category: 'Party Starters',
  },
  {
    video_id: 'LHCob76kigA',
    title: 'Idina Menzel - Let It Go (Frozen) (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
    duration: '3:45',
    category: 'Disney & Musicals',
  },
  {
    video_id: 'hLQl3WQQoQ0',
    title: 'Auliʻi Cravalho - How Far I’ll Go (Moana) (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80',
    duration: '2:55',
    category: 'Disney & Musicals',
  },
  {
    video_id: 'kXYiU_JCYtU',
    title: 'Linkin Park - Numb (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    duration: '3:07',
    category: 'Rock & 80s Classics',
  },
  {
    video_id: 'fRh_vgS2dFE',
    title: 'Justin Bieber - Sorry (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&auto=format&fit=crop&q=80',
    duration: '3:20',
    category: 'Pop & Today',
  },
  {
    video_id: 'ZbZSe6N_BXs',
    title: 'Pharrell Williams - Happy (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    duration: '3:53',
    category: 'Party Starters',
  },
  {
    video_id: '2Vv-BfVoq4g',
    title: 'Ed Sheeran - Thinking Out Loud (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
    duration: '4:41',
    category: 'Heartfelt Ballads',
  },
  {
    video_id: 'YVkUvmDQ3HY',
    title: 'Eminem - Without Me (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
    duration: '4:50',
    category: 'Party Starters',
  },
  {
    video_id: '04854XqcfCY',
    title: 'Queen - We Are The Champions (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    duration: '3:05',
    category: 'Rock & 80s Classics',
  },
  {
    video_id: '0HDdjwpPM3Y',
    title: 'Whitney Houston - I Will Always Love You (Karaoke)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1445985543470-41fdd6ce388d?w=600&auto=format&fit=crop&q=80',
    duration: '4:35',
    category: 'R&B & Soul',
  },
  {
    video_id: 'aJOTlE1K90k',
    title: 'Maroon 5 - Girls Like You (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
    duration: '3:55',
    category: 'Pop & Today',
  },
  {
    video_id: 'uelHwf8o7_U',
    title: 'Eminem ft. Rihanna - Love The Way You Lie (Karaoke)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&auto=format&fit=crop&q=80',
    duration: '4:23',
    category: 'Duets & Groups',
  },
  {
    video_id: 'pRpeEdMmmQ0',
    title: 'Shakira - Waka Waka (This Time for Africa) (Karaoke)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&auto=format&fit=crop&q=80',
    duration: '3:22',
    category: 'Party Starters',
  },
  {
    video_id: 'kJQP7kiw5Fk',
    title: 'Luis Fonsi ft. Daddy Yankee - Despacito (Karaoke)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&auto=format&fit=crop&q=80',
    duration: '3:48',
    category: 'Party Starters',
  },
  {
    video_id: 'RubBzkZzpUA',
    title: 'Passenger - Let Her Go (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1520523839898-507124cd5333?w=600&auto=format&fit=crop&q=80',
    duration: '4:15',
    category: 'Heartfelt Ballads',
  },
  {
    video_id: 'QKzcxA5aJkM',
    title: 'LiSA - Gurenge (Demon Slayer OP) (Karaoke Version)',
    channel_title: 'Karaoke Anime',
    thumbnail_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80',
    duration: '3:58',
    category: 'Anime & J-Pop',
  },
  {
    video_id: 'w4s4n1e9z9o',
    title: 'YOASOBI - IDOL (Oshi no Ko OP) (Karaoke Instrumental)',
    channel_title: 'Anime Karaoke World',
    thumbnail_url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
    duration: '3:33',
    category: 'Anime & J-Pop',
  },
  {
    video_id: 'e-ORhEE9VVg',
    title: 'Taylor Swift - Blank Space (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=600&auto=format&fit=crop&q=80',
    duration: '3:52',
    category: 'Pop & Today',
  },
  {
    video_id: 'hT_nvWreIhg',
    title: 'Eraserheads - Ang Huling El Bimbo (Karaoke Version)',
    channel_title: 'OPM Karaoke Collection',
    thumbnail_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    duration: '7:20',
    category: 'OPM Hits',
  },
  {
    video_id: 'kXYiU_JCYtU',
    title: 'Ben&Ben - Kathang Isip (Karaoke Version)',
    channel_title: 'OPM Karaoke Hub',
    thumbnail_url: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
    duration: '5:18',
    category: 'OPM Hits',
  },
];
