export interface CuratedTrack {
  video_id: string;
  title: string;
  channel_title: string;
  thumbnail_url: string;
  duration: string;
  category?: string;
}

export const POPULAR_KARAOKE_SONGS: CuratedTrack[] = [
  {
    video_id: '8yvGCAvOAfM',
    title: 'Queen - Bohemian Rhapsody (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    duration: '5:55',
    category: 'Rock Classics',
  },
  {
    video_id: '1k8craCGpgs',
    title: "Journey - Don't Stop Believin' (Karaoke Version)",
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
    duration: '4:11',
    category: 'Rock Classics',
  },
  {
    video_id: '450p7goxZqg',
    title: 'John Legend - All of Me (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1520523839898-507124cd5333?w=600&auto=format&fit=crop&q=80',
    duration: '4:30',
    category: 'Love & Ballads',
  },
  {
    video_id: 'L0MK7qz13bU',
    title: 'Frozen - Let It Go (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
    duration: '3:45',
    category: 'Disney & Movies',
  },
  {
    video_id: 'fJ9rUzIMcZQ',
    title: 'Queen - Don\'t Stop Me Now (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    duration: '3:30',
    category: 'Rock Classics',
  },
  {
    video_id: 'kJQP7kiw5Fk',
    title: 'Luis Fonsi, Daddy Yankee - Despacito (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80',
    duration: '3:48',
    category: 'Pop Anthems',
  },
  {
    video_id: 'hT_nvWreIhg',
    title: 'OneRepublic - Counting Stars (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
    duration: '4:17',
    category: 'Pop Anthems',
  },
  {
    video_id: '09R8_2nJtjg',
    title: 'Maroon 5 - Sugar (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&auto=format&fit=crop&q=80',
    duration: '3:55',
    category: 'Pop Anthems',
  },
  {
    video_id: 'CevxZvSJLk8',
    title: 'Katy Perry - Roar (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    duration: '3:43',
    category: 'Pop Anthems',
  },
  {
    video_id: 'e-ORhEE9VVg',
    title: 'Taylor Swift - Blank Space (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&auto=format&fit=crop&q=80',
    duration: '3:51',
    category: 'Pop Anthems',
  },
  {
    video_id: 'YQHsXMglC9A',
    title: 'Adele - Hello (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1520523839898-507124cd5333?w=600&auto=format&fit=crop&q=80',
    duration: '4:55',
    category: 'Love & Ballads',
  },
  {
    video_id: 'OPf0YbXqDm0',
    title: 'Mark Ronson ft. Bruno Mars - Uptown Funk (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
    duration: '4:30',
    category: 'Party Hits',
  },
  {
    video_id: 'kXYiU_JCYtU',
    title: 'Linkin Park - Numb (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    duration: '3:07',
    category: 'Rock Classics',
  },
  {
    video_id: 'uelHwf8o7_U',
    title: 'Eminem - Love The Way You Lie ft. Rihanna (Karaoke)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&auto=format&fit=crop&q=80',
    duration: '4:23',
    category: 'Hip-Hop & R&B',
  },
  {
    video_id: 'JGwWNGJdvx8',
    title: 'Ed Sheeran - Shape of You (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    duration: '3:53',
    category: 'Pop Anthems',
  },
  {
    video_id: 'nfWlot6h_JM',
    title: 'Taylor Swift - Shake It Off (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&auto=format&fit=crop&q=80',
    duration: '3:39',
    category: 'Pop Anthems',
  },
  {
    video_id: 'SlPhMPnQ58k',
    title: 'Maroon 5 - Memories (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1520523839898-507124cd5333?w=600&auto=format&fit=crop&q=80',
    duration: '3:09',
    category: 'Love & Ballads',
  },
  {
    video_id: '0KSOMA3QBU0',
    title: 'Katy Perry - Dark Horse (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    duration: '3:35',
    category: 'Pop Anthems',
  },
  {
    video_id: 'C_3d6GntKbk',
    title: 'Alicia Keys - If I Ain\'t Got You (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1520523839898-507124cd5333?w=600&auto=format&fit=crop&q=80',
    duration: '3:48',
    category: 'Love & Ballads',
  },
  {
    video_id: 'ZbZSe6N_BXs',
    title: 'Pharrell Williams - Happy (Karaoke Version)',
    channel_title: 'Sing King',
    thumbnail_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
    duration: '3:53',
    category: 'Party Hits',
  },
];
